// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bodyMCMC
Rcpp::List bodyMCMC(arma::vec y, int p, int nobs, arma::vec cd, arma::vec d, arma::mat X_l, arma::mat X_nl, arma::mat X_val_l, arma::mat X_val_nl, arma::vec hyperpar, arma::vec mht, int n_cat, int iter, int burnin, int thin, int ha, bool detail, bool pb);
RcppExport SEXP _invent_bodyMCMC(SEXP ySEXP, SEXP pSEXP, SEXP nobsSEXP, SEXP cdSEXP, SEXP dSEXP, SEXP X_lSEXP, SEXP X_nlSEXP, SEXP X_val_lSEXP, SEXP X_val_nlSEXP, SEXP hyperparSEXP, SEXP mhtSEXP, SEXP n_catSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP haSEXP, SEXP detailSEXP, SEXP pbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cd(cdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_l(X_lSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_nl(X_nlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_val_l(X_val_lSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_val_nl(X_val_nlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mht(mhtSEXP);
    Rcpp::traits::input_parameter< int >::type n_cat(n_catSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type ha(haSEXP);
    Rcpp::traits::input_parameter< bool >::type detail(detailSEXP);
    Rcpp::traits::input_parameter< bool >::type pb(pbSEXP);
    rcpp_result_gen = Rcpp::wrap(bodyMCMC(y, p, nobs, cd, d, X_l, X_nl, X_val_l, X_val_nl, hyperpar, mht, n_cat, iter, burnin, thin, ha, detail, pb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_invent_bodyMCMC", (DL_FUNC) &_invent_bodyMCMC, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_invent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
