# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myRange <- function(start, end) {
    .Call(`_invent_myRange`, start, end)
}

callrgamma <- function(n, shape, scale) {
    .Call(`_invent_callrgamma`, n, shape, scale)
}

updateInterceptC <- function(y, nobs, lp_noInt, sigma) {
    .Call(`_invent_updateInterceptC`, y, nobs, lp_noInt, sigma)
}

update_mCsca <- function(xi) {
    .Call(`_invent_update_mCsca`, xi)
}

update_mCvec <- function(xi) {
    .Call(`_invent_update_mCvec`, xi)
}

update_tauC <- function(at, bt, alpha, gamma) {
    .Call(`_invent_update_tauC`, at, bt, alpha, gamma)
}

deltaFNSC <- function(x, val) {
    .Call(`_invent_deltaFNSC`, x, val)
}

deltaFSC <- function(x, val) {
    .Call(`_invent_deltaFSC`, x, val)
}

update_piNSC <- function(ap, bp, gamma, v0) {
    .Call(`_invent_update_piNSC`, ap, bp, gamma, v0)
}

update_piSC <- function(ap, bp, gamma, v0) {
    .Call(`_invent_update_piSC`, ap, bp, gamma, v0)
}

update_sigmaC <- function(y, eta_pl, as, bs, nobs) {
    .Call(`_invent_update_sigmaC`, y, eta_pl, as, bs, nobs)
}

update_gammaScaC <- function(pi, v0, alpha, tau) {
    .Call(`_invent_update_gammaScaC`, pi, v0, alpha, tau)
}

update_gammaVecC <- function(pi, v0, alpha, tau) {
    .Call(`_invent_update_gammaVecC`, pi, v0, alpha, tau)
}

dnormLogVec <- function(x, means, sds) {
    .Call(`_invent_dnormLogVec`, x, means, sds)
}

update_alphaC <- function(y, sigma, tau, gamma, eta_star, eta_pl, alpha_star, alpha) {
    .Call(`_invent_update_alphaC`, y, sigma, tau, gamma, eta_star, eta_pl, alpha_star, alpha)
}

update_xiLC <- function(y, eta_star, eta_pl, sigma, m, xi_star, xi) {
    .Call(`_invent_update_xiLC`, y, eta_star, eta_pl, sigma, m, xi_star, xi)
}

update_xiNLC <- function(y, eta_star, eta_pl, sigma, m, xi_star, xi) {
    .Call(`_invent_update_xiNLC`, y, eta_star, eta_pl, sigma, m, xi_star, xi)
}

mysign <- function(x) {
    .Call(`_invent_mysign`, x)
}

compLinPred <- function(nobs, p, cd, eta0, X_l, beta_l, X_nl, beta_nl) {
    .Call(`_invent_compLinPred`, nobs, p, cd, eta0, X_l, beta_l, X_nl, beta_nl)
}

bodyMCMC <- function(y, p, nobs, cd, d, X_l, X_nl, hyperpar, mht, iter, burnin, thin, ha) {
    .Call(`_invent_bodyMCMC`, y, p, nobs, cd, d, X_l, X_nl, hyperpar, mht, iter, burnin, thin, ha)
}

