# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bodyMCMC <- function(y, p, nobs, cd, d, X_l, X_nl, X_val_l, X_val_nl, hyperpar, mht, n_cat, iter, burnin, thin, ha, detail = FALSE, pb = TRUE) {
    .Call(`_invent_bodyMCMC`, y, p, nobs, cd, d, X_l, X_nl, X_val_l, X_val_nl, hyperpar, mht, n_cat, iter, burnin, thin, ha, detail, pb)
}

